/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export interface Country {
  name: string;
  code: string;
  flag: string;
  launchHour: string;
}

export const COUNTRIES: Country[] = [
  { name: "Afghanistan", code: "+93", flag: "🇦🇫", launchHour: "23h30 (Heure de Kaboul)" },
  { name: "Afrique du Sud", code: "+27", flag: "🇿🇦", launchHour: "21h00 (Heure de Johannesburg)" },
  { name: "Algérie", code: "+213", flag: "🇩🇿", launchHour: "21h00 (Heure d'Alger)" },
  { name: "Allemagne", code: "+49", flag: "🇩🇪", launchHour: "22h00 (Heure de Berlin)" },
  { name: "Angola", code: "+244", flag: "🇦🇴", launchHour: "21h00 (Heure de Luanda)" },
  { name: "Arabie Saoudite", code: "+966", flag: "🇸🇦", launchHour: "22h00 (Heure de Riyad)" },
  { name: "Argentine", code: "+54", flag: "🇦🇷", launchHour: "16h00 (Heure de Buenos Aires)" },
  { name: "Australie", code: "+61", flag: "🇦🇺", launchHour: "05h00 (Heure de Sydney, le 5 Juillet)" },
  { name: "Autriche", code: "+43", flag: "🇦🇹", launchHour: "22h00 (Heure de Vienne)" },
  { name: "Belgique", code: "+32", flag: "🇧🇪", launchHour: "22h00 (Heure de Bruxelles)" },
  { name: "Bénin", code: "+229", flag: "🇧🇯", launchHour: "21h00 (Heure de Cotonou)" },
  { name: "Brésil", code: "+55", flag: "🇧🇷", launchHour: "16h00 (Heure de Brasília)" },
  { name: "Burkina Faso", code: "+226", flag: "🇧🇫", launchHour: "20h00 (Heure de Ouagadougou)" },
  { name: "Burundi", code: "+257", flag: "🇧🇮", launchHour: "21h00 (Heure de Gitega)" },
  { name: "Cameroun", code: "+237", flag: "🇨🇲", launchHour: "21h00 (Heure de Douala)" },
  { name: "Canada", code: "+1", flag: "🇨🇦", launchHour: "16h00 (Heure de Montréal)" },
  { name: "Centrafrique", code: "+236", flag: "🇨🇫", launchHour: "21h00 (Heure de Bangui)" },
  { name: "Chili", code: "+56", flag: "🇨🇱", launchHour: "16h00 (Heure de Santiago)" },
  { name: "Chine", code: "+86", flag: "🇨🇳", launchHour: "03h00 (Heure de Pékin, le 5 Juillet)" },
  { name: "Chypre", code: "+357", flag: "🇨🇾", launchHour: "22h00 (Heure de Nicosie)" },
  { name: "Colombie", code: "+57", flag: "🇨🇴", launchHour: "15h00 (Heure de Bogota)" },
  { name: "Comores", code: "+269", flag: "🇰🇲", launchHour: "22h00 (Heure de Moroni)" },
  { name: "Congo-Brazzaville", code: "+242", flag: "🇨🇬", launchHour: "21h00 (Heure de Brazzaville)" },
  { name: "Congo-Kinshasa (RDC)", code: "+243", flag: "🇨🇩", launchHour: "21h00 (Heure de Kinshasa)" },
  { name: "Côte d'Ivoire", code: "+225", flag: "🇨🇮", launchHour: "20h00 (Heure d'Abidjan)" },
  { name: "Danemark", code: "+45", flag: "🇩🇰", launchHour: "22h00 (Heure de Copenhague)" },
  { name: "Djibouti", code: "+253", flag: "🇩🇯", launchHour: "22h00 (Heure de Djibouti)" },
  { name: "Égypte", code: "+20", flag: "🇪🇬", launchHour: "22h00 (Heure du Caire)" },
  { name: "Émirats Arabes Unis", code: "+971", flag: "🇦🇪", launchHour: "23h00 (Heure de Dubaï)" },
  { name: "Espagne", code: "+34", flag: "🇪🇸", launchHour: "22h00 (Heure de Madrid)" },
  { name: "Estonie", code: "+372", flag: "🇪🇪", launchHour: "22h00 (Heure de Tallinn)" },
  { name: "États-Unis", code: "+1", flag: "🇺🇸", launchHour: "16h00 (Heure de New York)" },
  { name: "Éthiopie", code: "+251", flag: "🇪🇹", launchHour: "22h00 (Heure d'Addis-Abeba)" },
  { name: "Finlande", code: "+358", flag: "🇫🇮", launchHour: "22h00 (Heure de Helsinki)" },
  { name: "France", code: "+33", flag: "🇫🇷", launchHour: "22h00 (Heure de Paris)" },
  { name: "Gabon", code: "+241", flag: "🇬🇦", launchHour: "21h00 (Heure de Libreville)" },
  { name: "Gambie", code: "+220", flag: "🇬🇲", launchHour: "20h00 (Heure de Banjul)" },
  { name: "Ghana", code: "+233", flag: "🇬🇭", launchHour: "20h00 (Heure d'Accra)" },
  { name: "Grèce", code: "+30", flag: "🇬🇷", launchHour: "22h00 (Heure d'Athènes)" },
  { name: "Guinée", code: "+224", flag: "🇬🇳", launchHour: "20h00 (Heure de Conakry)" },
  { name: "Guinée-Bissau", code: "+245", flag: "🇬🇼", launchHour: "20h00 (Heure de Bissau)" },
  { name: "Guinée Équatoriale", code: "+240", flag: "🇬🇶", launchHour: "21h00 (Heure de Malabo)" },
  { name: "Haïti", code: "+509", flag: "🇭🇹", launchHour: "15h00 (Heure de Port-au-Prince)" },
  { name: "Inde", code: "+91", flag: "🇮🇳", launchHour: "00h30 (Heure de New Delhi, le 5 Juillet)" },
  { name: "Indonésie", code: "+62", flag: "🇮🇩", launchHour: "02h00 (Heure de Jakarta, le 5 Juillet)" },
  { name: "Irlande", code: "+353", flag: "🇮🇪", launchHour: "21h00 (Heure de Dublin)" },
  { name: "Italie", code: "+39", flag: "🇮🇹", launchHour: "22h00 (Heure de Rome)" },
  { name: "Japon", code: "+81", flag: "🇯🇵", launchHour: "04h00 (Heure de Tokyo, le 5 Juillet)" },
  { name: "Kenya", code: "+254", flag: "🇰🇪", launchHour: "22h00 (Heure de Nairobi)" },
  { name: "La Réunion", code: "+262", flag: "🇷🇪", launchHour: "00h00 (Heure de Saint-Denis, le 5 Juillet)" },
  { name: "Luxembourg", code: "+352", flag: "🇱🇺", launchHour: "22h00 (Heure de Luxembourg)" },
  { name: "Madagascar", code: "+261", flag: "🇲🇬", launchHour: "22h00 (Heure d'Antananarivo)" },
  { name: "Mali", code: "+223", flag: "🇲🇱", launchHour: "20h00 (Heure de Bamako)" },
  { name: "Maroc", code: "+212", flag: "🇲🇦", launchHour: "21h00 (Heure de Casablanca)" },
  { name: "Maurice", code: "+230", flag: "🇲🇺", launchHour: "23h00 (Heure de Port-Louis)" },
  { name: "Mauritanie", code: "+222", flag: "🇲🇷", launchHour: "20h00 (Heure de Nouakchott)" },
  { name: "Mayotte", code: "+262", flag: "🇾🇹", launchHour: "22h00 (Heure de Mamoudzou)" },
  { name: "Mexique", code: "+52", flag: "🇲🇽", launchHour: "14h00 (Heure de Mexico)" },
  { name: "Monaco", code: "+377", flag: "🇲🇨", launchHour: "22h00 (Heure de Monaco)" },
  { name: "Niger", code: "+227", flag: "🇳🇪", launchHour: "21h00 (Heure de Niamey)" },
  { name: "Nigeria", code: "+234", flag: "🇳🇬", launchHour: "21h00 (Heure de Lagos)" },
  { name: "Norvège", code: "+47", flag: "🇳🇴", launchHour: "22h00 (Heure d'Oslo)" },
  { name: "Nouvelle-Zélande", code: "+64", flag: "🇳🇿", launchHour: "07h00 (Heure de Wellington, le 5 Juillet)" },
  { name: "Pays-Bas", code: "+31", flag: "🇳🇱", launchHour: "22h00 (Heure d'Amsterdam)" },
  { name: "Pologne", code: "+48", flag: "🇵🇱", launchHour: "22h00 (Heure de Varsovie)" },
  { name: "Portugal", code: "+351", flag: "🇵🇹", launchHour: "21h00 (Heure de Lisbone)" },
  { name: "Qatar", code: "+974", flag: "🇶🇦", launchHour: "22h00 (Heure de Doha)" },
  { name: "Royaume-Uni", code: "+44", flag: "🇬🇧", launchHour: "21h00 (Heure de Londres)" },
  { name: "Rwanda", code: "+250", flag: "🇷🇼", launchHour: "21h00 (Heure de Kigali)" },
  { name: "Sénégal", code: "+221", flag: "🇸🇳", launchHour: "20h00 (Heure de Dakar)" },
  { name: "Seychelles", code: "+248", flag: "🇸🇨", launchHour: "23h00 (Heure de Victoria)" },
  { name: "Singapour", code: "+65", flag: "🇸🇬", launchHour: "03h00 (Heure de Singapour, le 5 Juillet)" },
  { name: "Suède", code: "+46", flag: "🇸🇪", launchHour: "22h00 (Heure de Stockholm)" },
  { name: "Suisse", code: "+41", flag: "🇨🇭", launchHour: "22h00 (Heure de Zurich)" },
  { name: "Tchad", code: "+235", flag: "🇹🇩", launchHour: "21h00 (Heure de N'Djamena)" },
  { name: "Togo", code: "+228", flag: "🇹🇬", launchHour: "20h00 (Heure de Lomé)" },
  { name: "Tunisie", code: "+216", flag: "🇹🇳", launchHour: "21h00 (Heure de Tunis)" },
  { name: "Turquie", code: "+90", flag: "🇹🇷", launchHour: "22h00 (Heure d'Istanbul)" },
  { name: "Viêt Nam", code: "+84", flag: "🇻🇳", launchHour: "02h00 (Heure de Hanoï, le 5 Juillet)" }
];
